#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-las-fs-wave
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las-fs-wave

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF3 $FEE_IF3 $CXI_IF3 $DEV_IF3 $SXR_IF3 $AMO_IF3 $XPP_IF3 $XCS_IF3 $MEC_IF3"

case "$1" in
start)
	cagstart las-fs-wave NET:CAG:LAS:FS:WAVE
	;;
stop)
	cagstop las-fs-wave
	;;
restart)
	cagrestart las-fs-wave
	;;
reload)
	cagreload NET:CAG:LAS:FS:WAVE
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

