#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-sxr-cam

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=sxr-cam
gwprefix=NET:CAG:SXR:CAM
gwprocport=30021

export EPICS_CA_ADDR_LIST=$SXR_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG2_IFLIST | sed -e "s%${SXR_IF2}%%"`
# Add the eth0 interface so we can use ca clients from the gateway host
export EPICS_CAS_INTF_ADDR_LIST="$EPICS_CAS_INTF_ADDR_LIST $IP"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
