#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-mec
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mec

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=mec
gwprefix=NET:CAG:MEC
gwprocport=30060

export EPICS_CA_ADDR_LIST=$MEC_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG1_IFLIST | sed -e "s%${MEC_IF1}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
