#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xppics
#
# Starts the EPICS CAG
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-xppics

# Source function library.
. /etc/init.d/functions
. ./epicscagp

gwname=mfxsmb
gwprefix=NET:CAG:MFXSMB
gwprocport=30332

export MFX_BCICS=172.21.46.255
export MFX_IFICS=172.21.46.185
export MFX_IFMFX=172.21.72.56

export EPICS_CA_ADDR_LIST="$MFX_BC"
#export EPICS_CAS_INTF_ADDR_LIST="$MFX_IFICS $IP"
export EPICS_CAS_INTF_ADDR_LIST="$MFX_IFICS"
export EPICS_CA_BEACON_PERIOD=20.0
export EPICS_CA_CONN_TMO=60.0
export EPICS_CA_MAX_ARRAY_BYTES=40000000
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO
export EPICS_CAS_IGNORE_ADDR_LIST="$MFX_IFICS $MFX_IFMFX"
export EPICS_CAS_BEACON_ADDR_LIST=$MFX_BC:5065
export DAEMON_COREFILE_LIMIT="unlimited"
export EPICS_CA_SERVER_PORT=5064
export EPICS_CAS_SERVER_PORT=5066

# cagdbg="-debug 9"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
