#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-ued
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-ued

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=ued
gwprefix=NET:CAG:UED
gwprocport=30200

export EPICS_CA_ADDR_LIST=$UED_BC
# Only to SRV!
#export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG01_IFLIST | sed -e "s%${UED_IF01}%%"`
export EPICS_CAS_INTF_ADDR_LIST=$SRV_IF01
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
