#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-mfx
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mfx

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=mfx
gwprefix=NET:CAG:MFX
gwprocport=30120

export EPICS_CA_ADDR_LIST=$MFX_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG3_IFLIST | sed -e "s%${MFX_IF3}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
