#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-fee
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-kmono

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF3 $MCC_IF3 $LAS_IF3 $THZ_IF3 $AMO_IF3 $SXR_IF3 $XPP_IF3 $XCS_IF3 $CXI_IF3 $MEC_IF3"
export EPICS_CA_MAX_ARRAY_BYTES=36000000

case "$1" in
start)
	cagstart fee-kmono NET:CAG:FEEKMONO
	;;
stop)
	cagstop fee-kmono
	;;
restart)
	cagrestart fee-kmono
	;;
reload)
	cagreload NET:CAG:FEEKMONO
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
