#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mcc

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=mcc-wave
gwprefix=NET:CAG:MCC:WAVE
gwprocport=30003

export EPICS_CA_ADDR_LIST=$MCC_GW
export EPICS_CA_SERVER_PORT=5079
export EPICS_CAS_INTF_ADDR_LIST="$AMO_IF3 $LAS_IF3 $FEE_IF3 $DEV_IF3 $XPP_IF3 $SXR_IF3 $TST_IF3 $XCS_IF3 $CXI_IF3 $MEC_IF3 $IP"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
