#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xppics
#
# Starts the EPICS CAG
#
# description: EPICS Channel Access Gateway
# processname: epicscagd-xppics

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=xppics
gwprefix=NET:CAG:XPPICS
gwprocport=30100

export XPP_BCICS=172.21.46.255
export XPP_IFICS=172.21.46.22
export XPP_IFXPP=172.21.38.54
export XPP_IFFEZ=172.21.22.54

export EPICS_CA_ADDR_LIST=$XPP_BC
export EPICS_CAS_INTF_ADDR_LIST="$XPP_IFICS $IP"
export EPICS_CA_BEACON_PERIOD=20.0
export EPICS_CA_CONN_TMO=60.0
export EPICS_CA_MAX_ARRAY_BYTES=8000000
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO
export EPICS_CAS_IGNORE_ADDR_LIST="$XPP_IFICS $XPP_IFXPP $XPP_IFFEZ"
export EPICS_CAS_BEACON_ADDR_LIST=$XPP_BCICS:5065
export DAEMON_COREFILE_LIMIT="unlimited"
export EPICS_CA_SERVER_PORT=5064
export EPICS_CAS_SERVER_PORT=5066

# cagdbg="-debug 9"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
