#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-uedfac
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-uedfac

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=txi-ics
gwprefix=NET:CAG:TXI:ICS
gwprocport=30204

export EPICS_CA_ADDR_LIST=$TXI_BC
export EPICS_CAS_INTF_ADDR_LIST=$PSCAGTXI_ICSIF
export EPICS_CAS_IGNORE_ADDR_LIST=""

#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
