#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-cxi
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-cxi

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=cxi
gwprefix=NET:CAG:CXI
gwprocport=30050

export EPICS_CA_ADDR_LIST=$CXI_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG1_IFLIST | sed -e "s%${CXI_IF1}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
