#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-cam

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee-cam
gwprefix=NET:CAG:FEE:CAM
gwprocport=30071

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG3_IFLIST | sed -e "s%${FEE_IF3}%%"`

#cagdbg="-debug 5"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
