#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las-sxr

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=las-sxr
gwprefix=NET:CAG:LAS:SXR
gwprocport=30092

export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG1_IFLIST | sed -e "s%${LAS_IF1}%%"`
# Add the eth0 interface so we can use ca clients from the gateway host
export EPICS_CAS_INTF_ADDR_LIST="$EPICS_CAS_INTF_ADDR_LIST $IP"

#cagprogram="/reg/neh/home/bhill/wa2/trunk/pcds/epics/extensions/current/bin/linux-x86_64/pvgwfd"
case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
