#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-fee-arrays
#
# Starts the EPICS CAG
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-arrays

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee-arrays
gwprefix=NET:CAG:FEE:ARRAYS
gwprocport=30077

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG4_IFLIST | sed -e "s%${FEE_IF4}%%"`
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
