#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-facued-cam
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-facued-cam

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=facued-cam
gwprefix=NET:CAG:FACUED:CAM
gwprocport=30200

export EPICS_CA_ADDR_LIST=$FAC_BC
export EPICS_CAS_INTF_ADDR_LIST=$PSCAGUED_UEDIF
export EPICS_CAS_IGNORE_ADDR_LIST="$PSCAGUED_FACIF $PSCAGUED_UEDIF"
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
