#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-sxr
#
# Starts the EPICS CAG gateway
#
# description: EPICS Channel Access Gateway
# processname: epicscagd-sxr

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=sxr
gwprefix=NET:CAG:SXR
gwprocport=30020

export EPICS_CA_ADDR_LIST=$SXR_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF1 $LAS_IF1 $FEE_IF1 $DEV_IF1 $XPP_IF1 $AMO_IF1 $TST_IF1 $XCS_IF1 $CXI_IF1 $MEC_IF1"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
