#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-facued
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-facued

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=facued
gwprefix=NET:CAG:FACUED
gwprocport=30202

export EPICS_CA_ADDR_LIST=$FAC_BC
export EPICS_CAS_INTF_ADDR_LIST=$PSCAGUED_UEDIF
export EPICS_CAS_IGNORE_ADDR_LIST="$PSCAGUED_FACIF $PSCAGUED_UEDIF"
export EPICS_CAS_IGNORE_ADDR_LIST="$EPICS_CAS_IGNORE_ADDR_LIST ued-daq ued-monitor"
export EPICS_CAS_IGNORE_ADDR_LIST="$EPICS_CAS_IGNORE_ADDR_LIST ioc-ued-ccd01 drp-ued-cmp001 drp-ued-cmp002"
export EPICS_CAS_IGNORE_ADDR_LIST="$EPICS_CAS_IGNORE_ADDR_LIST ctl-ued-pgp-01 ctl-ued-cam-01"
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
