#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-kfe-gmd
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-kfe-gmd

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=kfe-gmd
gwprefix=NET:CAG:KFE:GMD
gwprocport=30022

export EPICS_CA_ADDR_LIST=$KFE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG4_IFLIST | sed -e "s%${KFE_IF4}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
