#!/bin/bash
#
# Gateway pvlist config file for tst-lab2 on pscaglab2 in B84
#
#	/etc/rc.d/init.d/epicscagd-tst-lab2
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-tst-lab2

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=tst-lab2
gwprefix=NET:CAG:TST:LAB2
gwprocport=30130

export EPICS_CA_ADDR_LIST=$LAB2_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAGLAB2_IFLIST | sed -e "s%${TST_IFLAB2}%%"`
#export cagprogram=/reg/neh/home/bhill/wa2/trunk/pcds/epics/extensions/current/bin/${EPICS_HOST_ARCH}/gateway
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	echo Running: cagstart $gwname $gwprefix $gwprocport
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
