#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-kfe
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-kfe

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=kfe
gwprefix=NET:CAG:KFE
gwprocport=30023

export EPICS_CA_ADDR_LIST=$KFE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG01_IFLIST | sed -e "s%${KFE_IF01}%%"`

case "$1" in
start)
	TIME=`date +%Y_%m_%d-%T`
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
