#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-cam

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee-cam
gwprefix=NET:CAG:FEE:CAM
gwprocport=30071

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF2 $MCC_IF2 $LAS_IF2 $THZ_IF2 $AMO_IF2 $SXR_IF2 $XPP_IF2 $TST_IF2 $XCS_IF2 $CXI_IF2 $MEC_IF2 $IP"
export EPICS_CA_MAX_ARRAY_BYTES=36000000

#cagprogram="/reg/neh/home/bhill/wa2/trunk/pcds/epics/extensions/current/bin/linux-x86_64/pvgwfd"
case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
