#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-det

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=det
gwprefix=NET:CAG:DET
gwprocport=30074

export EPICS_CA_ADDR_LIST=$DET_BC
export EPICS_CAS_INTF_ADDR_LIST="$FEE_IF2 $DEV_IF2 $MCC_IF2 $LAS_IF2 $THZ_IF2 $AMO_IF2 $SXR_IF2 $XPP_IF2 $TST_IF2 $XCS_IF2 $CXI_IF2 $MEC_IF2 $IP"
export EPICS_CA_MAX_ARRAY_BYTES=40000000

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
