#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-lfe
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-lfe

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=lfe
gwprefix=NET:CAG:LFE
gwprocport=30070
export gwHostNum=02

export EPICS_CA_ADDR_LIST=$LFE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG02_IFLIST | sed -e "s%${LFE_IF02}%%"`
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
