#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-cam2

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee-cam2
gwprefix=NET:CAG:FEE:CAM2
gwprocport=30078

export EPICS_CA_ADDR_LIST=$HXR_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG4_IFLIST | sed -e "s%${LFE_IF4}%%"`

#cagdbg="-debug 5"
#cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/pvgwfd"

#cagstart() {
#  echo -n "Starting $1 gateway... "
#  TIME=`date +%Y_%m_%d-%T`
#  mkdir -p $cagvardir/$1
#  /bin/rm -f $cagvardir/$1/gateway.log
#  /bin/rm -f $cagvardir/$1/gateway-put.log
#  ln -s $cagvardir/$1/gateway.log.$TIME $cagvardir/$1/gateway.log
#  ln -s $cagvardir/$1/gateway-put.log.$TIME $cagvardir/$1/gateway-put.log
#  PROCSERV="$procServ --allow --ignore ^D^C --logfile $cagvardir/$1/gateway.log.$TIME --name $1 $3"
#  $PROCSERV $cagprogram -access $cagcfgdir/pcds-access.acf -pvlist $cagcfgdir/$1.pvlist -home $cagvardir/$1 $cagdbg -prefix $2 -command $cagvardir/gateway.command $4 $5 $6 $7 
#  echo " done"
#}

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
