#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-fee
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee
gwprefix=NET:CAG:FEE
gwprocport=30070

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF1 $LAS_IF1 $CXI_IF1 $DEV_IF1 $SXR_IF1 $AMO_IF1 $XPP_IF1 $TST_IF1 $XCS_IF1 $MEC_IF1 $IP"
#export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF1 $MCC_IF1 $LAS_IF1 $THZ_IF1 $AMO_IF1 $SXR_IF1 $XPP_IF1 $TST_IF1 $XCS_IF1 $CXI_IF1 $MEC_IF1 $IP"
#export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF2 $MCC_IF2 $LAS_IF2 $THZ_IF2 $AMO_IF2 $SXR_IF2 $XPP_IF2 $TST_IF2 $XCS_IF2 $CXI_IF2 $MEC_IF2 $IP"
#export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF3 $MCC_IF3 $LAS_IF3 $THZ_IF3 $AMO_IF3 $SXR_IF3 $XPP_IF3 $TST_IF3 $XCS_IF3 $CXI_IF3 $MEC_IF3 $IP"
export EPICS_CA_MAX_ARRAY_BYTES=36000000

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
