#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xpp
#
# Starts the EPICS CAG
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-xpp

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=xpp
gwprefix=NET:CAG:XPP
gwprocport=30030

export EPICS_CA_ADDR_LIST=$XPP_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG3_IFLIST | sed -e "s%${XPP_IF3}%%"`
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
