#!/bin/bash
#
# description: Channel Access Gateway Test Script
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-test1

. /reg/g/pcds/gateway/scripts/epicscagp

# Development testing alternate cagprogram
cagprogram="/reg/neh/home2/bhill/wa2/trunk/pcds/epics/extensions/current/bin/linux-x86_64/gateway"


gwname=test1
gwprefix=NET:CAG:TEST1
gwprocport=30920

# Use /tmp/gateway for gateway output while testing
cagvardir=/tmp/gateway
mkdir -p $cagvardir/$gwname

# Get the eth0 IP addr
export IP=`/sbin/ifconfig eth0 | /bin/grep 'inet addr:' | /bin/cut -d: -f2 | /bin/awk '{ print $1 }'`

export EPICS_CA_AUTO_ADDR_LIST=YES
unset EPICS_CA_ADDR_LIST
export EPICS_CAS_SERVER_PORT=5081
export EPICS_CAS_INTF_ADDR_LIST="127.0.0.1 $IP"
#export EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO
#export EPICS_CAS_IGNORE_ADDR_LIST="$LAS_IF1 $LAS_IF2 ... $MEC_IF3"
#export EPICS_CAS_BEACON_ADDR_LIST="$DEV_BC:5065 $MCC_BC:5069 $FEE_BC:5065 $AMO_BC:5065 ... $MEC_BC:5065"

cagstart() {
  echo -n "Starting $1 gateway... "
  TIME=`date +%s`
  PROCSERV="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/linux-x86_64/procServ --allow --ignore ^D^C --logfile gateway.log.$TIME --name $1 $3"
  $PROCSERV $cagprogram -access $cagcfgdir/hosts -pvlist $cagcfgdir/test1.pvlist -home $cagvardir/$1 -prefix $2 
  echo " done"
}

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
