#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-srv
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mec

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=srv
gwprefix=NET:CAG:SRV
gwprocport=30666
export gwHostNum=01

export EPICS_CAS_SERVER_PORT=5068
export EPICS_CA_ADDR_LIST=`echo $BC_LIST | sed -e "s%${DEV_BC}%%" -e "s%${MCC1_BC}%%"  -e "s%${MCC2_BC}%${MCC_GW}:5080%"`
export EPICS_CAS_INTF_ADDR_LIST=$SRV_IF01

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
