#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-lfe-gdet-arrays2

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=lfe-gdet-arrays2
gwprefix=NET:CAG:LFE:GDET:ARRAYS2
gwprocport=30072

export EPICS_CA_ADDR_LIST=$LFE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG06_IFLIST | sed -e "s%${LFE_IF06}%%"`

# Add -no_cache to gwargs to disable caching in gateway
# With -no_cache, CA updates are passed along to clients w/o pre-fetching the value.
gwargs="$gwargs -no_cache"

case "$1" in
start)
	echo Running: cagstart $gwname $gwprefix $gwprocport $gwargs
	cagstart $gwname $gwprefix $gwprocport $gwargs
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
