#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las-und-misc

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=las-und-misc
gwprefix=NET:CAG:LAS:UND:MISC
gwprocport=30099

export IP=`/sbin/ifconfig eth0 | /bin/grep 'inet addr:' | /bin/cut -d: -f2 | /bin/awk '{ print $1 }'`
export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF3 $FEE_IF3 $CXI_IF3 $DEV_IF3 $SXR_IF3 $AMO_IF3 $XPP_IF3 $TST_IF3 $XCS_IF3 $MEC_IF3 $IP"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start}"
	exit 1
esac

exit $?
