#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-tmo

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=tmo
gwprefix=NET:CAG:TMO
gwprocport=30079

export EPICS_CA_ADDR_LIST=$TMO_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG03_IFLIST | sed -e "s%${TMO_IF03}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
