#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-mec
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mec

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$MEC_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $CDS_IF $FEE_IF $DEV_IF $XPP_IF $SXR_IF $XCS_IF $CXI_IF $AMO_IF"

case "$1" in
start)
	cagstart mec NET:CAG:MEC
	;;
stop)
	cagstop mec
	;;
restart)
	cagrestart mec
	;;
reload)
	cagreload NET:CAG:MEC
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

