#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=las
gwprefix=NET:CAG:LAS
gwprocport=30090
export gwHostNum=01

export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG01_IFLIST | sed -e "s%${LAS_IF01}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
