#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-mec
#
# Starts the EPICS CAG
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mec

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=mec-arrays
gwprefix=NET:CAG:MEC:ARRAYS
gwprocport=30061
export EPICS_CA_ADDR_LIST=$MEC_BC

# Make sure you update gateway host number in all 3 places in the following lines!
export gwHostNum=01
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG01_IFLIST | sed -e "s%${MEC_IF01}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
