#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xcs
#
# Starts the EPICS CAG
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-xcs

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=xcs-arrays
gwprefix=NET:CAG:XCS:ARRAYS
gwprocport=30041
export gwHostNum=03

export EPICS_CA_ADDR_LIST=$XCS_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG04_IFLIST | sed -e "s%${XCS_IF04}%%"`
#export cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache 
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
