#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xcs
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-xcs

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$XCS_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $CDS_IF $FEE_IF $DEV_IF $SXR_IF $AMO_IF $XPP_IF $CXI_IF"

case "$1" in
start)
	cagstart xcs NET:CAG:XCS
	;;
stop)
	cagstop xcs
	;;
restart)
	cagrestart xcs
	;;
reload)
	cagreload NET:CAG:XCS
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

