#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las-fs-wave

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=las-fs-wave
gwprefix=NET:CAG:LAS:FS:WAVE
gwprocport=30097
export gwHostNum=03

export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG03_IFLIST | sed -e "s%${LAS_IF03}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start}"
	exit 1
esac

exit $?
