#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-fee
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-camfeh

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST="$DEV_IF2 $MCC_IF2 $LAS_IF2 $THZ_IF2 $AMO_IF2 $SXR_IF2 $XPP_IF2 $XCS_IF2 $CXI_IF2 $MEC_IF2"
export EPICS_CA_MAX_ARRAY_BYTES=36000000

case "$1" in
start)
	cagstart fee-camfeh NET:CAG:FEECAMFEH
	;;
stop)
	cagstop fee-camfeh
	;;
restart)
	cagrestart fee-camfeh
	;;
reload)
	cagreload NET:CAG:FEECAMFEH
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
