#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-det

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=det
gwprefix=NET:CAG:DET
gwprocport=30074
export gwHostNum=02

export EPICS_CA_ADDR_LIST=$DET_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG02_IFLIST | sed -e "s%${DET_IF02}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
