#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-kmono

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee-kmono
gwprefix=NET:CAG:FEE:KMONO
gwprocport=30075

export EPICS_CA_ADDR_LIST=$HXR_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG3_IFLIST | sed -e "s%${LFE_IF3}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport -no_cache
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
