#!/bin/bash
# Must verify the host, upstream sources, listener, ports, and -ro support.
#
#	/etc/rc.d/init.d/epicscagd-srv
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-nalms

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=ued-sdf-ai
gwprefix=NET:CAG:UED:SDF:AI
gwprocport=31001				# 31000–31099 range is available
export gwHostNum=01

# Special port so normal clients don't see this
export EPICS_CAS_SERVER_PORT=5110	# 5110–5119 range is available
# Explicit list of areas to search in for data
export EPICS_CA_ADDR_LIST="$UED_BC"
# Explicit interfaces on pscag01 to allow access to
export EPICS_CAS_INTF_ADDR_LIST="$S3DF_IF01"

# Special access rules
cagacf="$cagcfgdir/$gwname.acf"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
