#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-fee
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=fee
gwprefix=NET:CAG:FEE
gwprocport=30070

export EPICS_CA_ADDR_LIST=$FEE_BC
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG2_IFLIST | sed -e "s%${FEE_IF2}%%"`

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
