#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-tst
#
# Starts the EPICS CAG gateway
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-tst

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagp

gwname=tst
gwprefix=NET:CAG:TST
gwprocport=30110

export EPICS_CA_ADDR_LIST=$TST_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF3 $LAS_IF3 $FEE_IF3 $DEV_IF3 $AMO_IF3 $XPP_IF3 $SXR_IF3 $XCS_IF3 $CXI_IF3 $MEC_IF3 $IP"

case "$1" in
start)
	cagstart $gwname $gwprefix $gwprocport
	;;
name)
	echo "Gateway $gwname (prefix $gwprefix) runs on procServ port $gwprocport"
	;;
*)
	echo $"Usage: $0 {start|name}"
	exit 1
esac

exit $?
