#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-thz
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-thz

# Source function library.
. /etc/init.d/functions
#. /etc/init.d/epicscagd
. /etc/init.d/epicscagd-3.14.12-pvgwfd

RETVAL=0

export EPICS_CA_ADDR_LIST=$THZ_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF1 $DEV_IF1"

case "$1" in
start)
	cagstart thz NET:CAG:THZ
	;;
stop)
	cagstop thz
	;;
restart)
	cagrestart thz
	;;
reload)
	cagreload NET:CAG:THZ
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

