#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-las
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-las

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$LAS_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF1 $FEE_IF1 $CXI_IF1 $DEV_IF1 $SXR_IF1 $AMO_IF1 $XPP_IF1 $XCS_IF1 $MEC_IF1"

case "$1" in
start)
	cagstart las NET:CAG:LAS
	;;
stop)
	cagstop las
	;;
restart)
	cagrestart las
	;;
reload)
	cagreload NET:CAG:LAS
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

