#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-fee-cam3

# Source function library.
. /etc/init.d/functions
. /reg/g/pcds/gateway/scripts/epicscagp

gwname=fee-cam-test
gwprefix=NET:CAG:FEE:CAM:TEST
gwprocport=30079

export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST=$FEE_BC
#export EPICS_CA_SERVER_PORT=5084
#export EPICS_CA_REPEATER_PORT=5083
export EPICS_CAS_BEACON_PORT=5083
export EPICS_CAS_SERVER_PORT=5084
export EPICS_CAS_BEACON_ADDR_LIST="$MCC_BC:5083 $MCC2_BC:5083"
export EPICS_CAS_IGNORE_ADDR_LIST="$ALL_PSCAG_IFLIST"
#export EPICS_CAS_IGNORE_ADDR_LIST="$DEV_IF1 $DEV_IF3 $DEV_IF4"
#export EPICS_CAS_INTF_ADDR_LIST=172.21.46.35
export EPICS_CAS_INTF_ADDR_LIST=`echo $PSCAG4_IFLIST | sed -e "s%${FEE_IF4}%%"`

cagdbg="-debug 12"
#cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/pvgwfd"
#cagprogram="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/gateway"
cagprogram="/reg/g/pcds/epics/extensions/gateway/R2.0.6.0-1.0.0/bin/$EPICS_HOST_ARCH/gateway"

mkdir --parents /tmp/$gwname
$cagprogram -access $cagcfgdir/hosts -pvlist $cagcfgdir/$gwname.pvlist -log /tmp/$gwname/gateway.log -home /tmp/$gwname $cagdbg 2>&1 > /tmp/$gwname/gateway-out.log &
#cagstart $gwname $gwprefix $gwprocport
