#!/bin/bash
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-test1

# Source function library.
. /etc/init.d/functions
. /reg/g/pcds/gateway/scripts/epicscagp

gwname=tst
gwprefix=NET:CAG:TEST1
gwprocport=30081
export gwHostNum=06

export EPICS_CA_ADDR_LIST=$TST_BC
SUBNET_IF_REF=TST_IF${gwHostNum}
IFLIST_REF=PSCAG${gwHostNum}_IFLIST

export EPICS_CAS_INTF_ADDR_LIST=`echo ${!IFLIST_REF} | sed -e "s%${!SUBNET_IF_REF}%%"`

cagprogram="/reg/g/pcds/epics-dev/bhill/extensions/ca-gateway-git/bin/$EPICS_HOST_ARCH/gateway"
#cagprogram="/reg/g/pcds/epics/extensions/gateway/R2.1.2.0-1.3.0/bin/$EPICS_HOST_ARCH/gateway"
#cagprogram="/reg/g/pcds/epics/extensions/gateway/R2.1.2.0-1.4.0/bin/$EPICS_HOST_ARCH/gateway"

#export EPICS_CA_SERVER_PORT=5084
#export EPICS_CA_REPEATER_PORT=5083
export EPICS_CAS_BEACON_PORT=5083
export EPICS_CAS_SERVER_PORT=5084
#export EPICS_CAS_BEACON_ADDR_LIST="$SXR_BC:5083 $XPP_BC:5083 $XCS_BC:5083 "
#export EPICS_CAS_IGNORE_ADDR_LIST="$ALL_PSCAG_IFLIST"
#export EPICS_CAS_IGNORE_ADDR_LIST="$DEV_IF01 $DEV_IF03 $DEV_IF04"
#export EPICS_CAS_INTF_ADDR_LIST=172.21.46.35

cagdbg="-debug 15"

mkdir --parents /tmp/$gwname
$cagprogram -access $cagcfgdir/pcds-access.acf -pvlist $cagcfgdir/$gwname.pvlist -home /tmp/$gwname $cagdbg 2>&1 | tee /tmp/$gwname/gateway.log
#cagstart $gwname $gwprefix $gwprocport
