#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-cds
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-cds

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$CDS_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $FEE_IF $CXI_IF $DEV_IF $SXR_IF $AMO_IF $XPP_IF $XCS_IF"

case "$1" in
start)
	cagstart cds NET:CAG:CDS
	;;
stop)
	cagstop cds
	;;
restart)
	cagrestart cds
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

