#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-amo
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-amo

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$AMO_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $CDS_IF $FEE_IF $DEV_IF $XPP_IF $SXR_IF $XCS_IF $CXI_IF $MEC_IF"

case "$1" in
start)
	cagstart amo NET:CAG:AMO
	;;
stop)
	cagstop amo
	;;
restart)
	cagrestart amo
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

