#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-mcc
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-mcc

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$MCC_GW
export EPICS_CA_SERVER_PORT=5080
export EPICS_CAS_BEACON_ADDR_LIST="$CDS_BC:5065 $FEE_BC:5065 $AMO_BC:5065 $DEV_BC:5065 $XPP_BC:5065 $SXR_BC:5065 $XCS_BC:5065 $CXI_BC:5065"
export EPICS_CAS_INTF_ADDR_LIST="$AMO_IF $CDS_IF $FEE_IF $DEV_IF $XPP_IF $SXR_IF $XCS_IF $CXI_IF"

case "$1" in
start)
	cagstart mcc NET:CAG:MCC
	;;
stop)
	cagstop mcc
	;;
restart)
	cagrestart mcc
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

