#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-thz
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-thz

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$THZ_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $DEV_IF"

case "$1" in
start)
	cagstart thz NET:CAG:THZ
	;;
stop)
	cagstop thz
	;;
restart)
	cagrestart thz
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

