#!/bin/bash
#
#	/etc/rc.d/init.d/epicscagd-xpp
#
# Starts the EPICS CAG daemon
#
# chkconfig: - 99 1
# description: EPICS Channel Access Gateway
# processname: epicscagd-xpp

# Source function library.
. /etc/init.d/functions
. /etc/init.d/epicscagd

RETVAL=0

export EPICS_CA_ADDR_LIST=$XPP_BC
export EPICS_CAS_INTF_ADDR_LIST="$MCC_IF $CDS_IF $FEE_IF $DEV_IF $SXR_IF $AMO_IF $XCS_IF $CXI_IF"

case "$1" in
start)
	cagstart xpp NET:CAG:XPP
	;;
stop)
	cagstop xpp
	;;
restart)
	cagrestart xpp
	;;
*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

